x = int(input("Digite um numero inteiro: "))
y = int(input("Digite outro numero inteiro: "))
z = int(input("Digite um numero real: "))
print("")
print("o produto do dobro do primeiro com metade do segundo: ",(x*2)+(y/2))
print("")
print("a soma do triplo do primeiro com o terceiro: ",(x*3)+z)
print("")
print("o terceiro elevado ao cubo: ",z**3)
