print("Calculadora de média anual")
b1 = int(input("Digite a nota do primeiro Bimestre do aluno: "))
b2 = int(input("Digite a nota do segundo Bimestre do aluno: "))
b3 = int(input("Digite a nota do terceiro Bimestre do aluno: "))
b4 = int(input("Digite a nota do quarto Bimestre do aluno: "))
print("A média do aluno é: ", (b1+b2+b3+b4)//4)
